In [4]:
# numpy - a library for creating n dimensional array

import numpy as np

a = [12,25,37,62]

arr1 = np.array(a)

b = [46,18,81,29]

arr2 = np.array(b)
print(type(arr1))

print(arr1)
print(arr2)

print(a+b)
print(arr1+arr2)

<class 'numpy.ndarray'>
[12 25 37 62]
[46 18 81 29]
[12, 25, 37, 62, 46, 18, 81, 29]
[ 58  43 118  91]


In [5]:
# linspace - create an array within a small range

arr1 = np.linspace(0.2,0.7,50)

print(arr1)

[0.2        0.21020408 0.22040816 0.23061224 0.24081633 0.25102041
 0.26122449 0.27142857 0.28163265 0.29183673 0.30204082 0.3122449
 0.32244898 0.33265306 0.34285714 0.35306122 0.36326531 0.37346939
 0.38367347 0.39387755 0.40408163 0.41428571 0.4244898  0.43469388
 0.44489796 0.45510204 0.46530612 0.4755102  0.48571429 0.49591837
 0.50612245 0.51632653 0.52653061 0.53673469 0.54693878 0.55714286
 0.56734694 0.57755102 0.5877551  0.59795918 0.60816327 0.61836735
 0.62857143 0.63877551 0.64897959 0.65918367 0.66938776 0.67959184
 0.68979592 0.7       ]
